name: Deploy to Vercel
on:
  push:
    branches:
      - master
  workflow_dispatch: 
jobs: 
  Deploy-Production:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: echo-dos-bons
        run: echo "e aí meu bom"
        
      - name: Stage 1 - Instala o cli da vercel
        run: npm install --global vercel@latest

      - name: Stage 2 - Pull Vercel token
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Stage 3 - Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Stage 4 - Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
